### ISSUE TITLE
Text color

### ISSUE THREAD

**Issue by marcpops** [tana-gh/vector-replace#14]
Hi,
I have a light vscode workbench theme.
When I use the vector-replace extension, the text labels of the checkboxes are in the same dark color as the text in the workbench theme (dark text on light background).
But the background color of the vector-replace pane is black (dark text on black background).
So it is not readable.
Thanks

![Capture-ecran 2021-09-09 à 07 50 47](https://user-images.githubusercontent.com/75844886/132630509-e37347c0-168c-414e-899e-156a6292ed53.png)

**Comment by tana-gh** [comment]
Hi,
This is a bug in stylesheet, so I will fix it soon.
Thanks for nice issue.
